name: Flujo de trabajo para eventos cron   # El nombre del flujo de trabajo debe ser lo mas descriptivo posible

on: 
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world desde mi step
        run: echo "Hola mundo desde mi step.."